[build]
  publish = "public"
  command = "gatsby build"
[build.environment]
  YARN_VERSION = "1.3.2"
  YARN_FLAGS = "--no-ignore-optional"
[[redirects]]
  from = "hopeful-cray-fede73.netlify.com/*"
  to = "https://1piece.me/:splat"
  force = true